export let questionBank = [
    "E question",
    "N question",
    "T question",
    "P question",
    "I question",
    "S question",
    "F question",
    "J question",
    "E question",
    "N question",
    "T question",
    "P question",
    "I question",
    "S question",
    "F question",
    "J question",
    "wine question 1",
    "wine question 2",
    "wine question 3",
    "wine question 4",
]